server:
  port: 9000
spring:
  application:
    name: next-talk-ai
langchain4j:
  open-ai:
    chat-model:
      api-key: your key
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
